// <auto-generated />
namespace KudevolveWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class bambina : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bambina));
        
        string IMigrationMetadata.Id
        {
            get { return "201411082001405_bambina"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
